### PR TITLE
Added feedback to form through a radix toast using the validateStep

### LINKED ISSUE #77: Add proper user feedback to Application form

### PR DESCRIPTION
**Pull request by markulon**
By using the validateStep function in the applicationForm.tsx file the content of a hidden toast message is updated to include a list of the missing fields when attempting to submit or go to the next page.

The toast is shown when there are erros and is hidden when there are no errors when clicking the buttons.

The solution is very bare-boned and simple but it does work

### CODE REVIEW

**Comment by steffenhaeren** [comment]
Nice work!

For the consent page, I dont get any alert saying what checkboxes are missing. Could you take a look at this?

Also, are you able to make the text in alert more readable by adding breaklines and maybe an unordered list?

**Comment by markulon** [comment]
image

Can you show me how it looks like on your computer because this is what i see, and i believe it fits what you ask for or am i misunderstanding?

**Comment by markulon** [comment]
Fixed the issue where some code was lacking from the branch

**Comment by steffenhaeren** [comment]
Awesome work, looks great!

**Pull request merged**
